apiVersion: devopstoolkit.live/v1alpha1
kind: AppClaim
metadata:
  name: silly-demo
  labels:
    app-owner: vfarcic
spec:
  id: silly-demo
  compositionSelector:
    matchLabels:
      type: backend
      location: local
  parameters:
    namespace: a-team
    image: ghcr.io/vfarcic/idp-full-app
    tag: 0.0.1
    port: 8080
    host: silly-demo.48.216.135.224.nip.io
    ingressClassName: contour
    db:
      secret: silly-demo-db-20250114145525
    repository:
      enabled: true
      name: idp-full-app
    ci:
      enabled: true
